name: Build Flet APK

on:
  push:
    branches: [master, main]
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: "3.10"  # استخدام إصدار مدعوم
  FLUTTER_VERSION: "3.22.2"

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          python3-tk \
          libgtk-3-dev \
          openjdk-17-jdk \
          build-essential \
          zlib1g-dev \
          libncurses5-dev \
          libgdbm-dev \
          libnss3-dev \
          libssl-dev \
          libsqlite3-dev \
          libreadline-dev \
          libffi-dev \
          libbz2-dev
        sudo apt-get clean

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flet deep_translator

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: stable

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android licenses
      run: |
        yes | sdkmanager --licenses
        flutter doctor --android-licenses

    - name: Verify environment
      run: flutter doctor -v

    - name: Build APK with Flet
      run: |
        flet build apk \
          --build-number ${{ env.BUILD_NUMBER }} \
          --build-version ${{ env.BUILD_VERSION }} \
          --verbose

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/*.apk
